runtime: python
env: flex
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

runtime_config:
  python_version: 3

env_variables:
  LMNOP_DB_PW: password_here

beta_settings:
  cloud_sql_instances: lmnop-2905:us-central1:lmnop