# Generated by Django 2.0.3 on 2018-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='pkey',
            field=models.IntegerField(blank=True),
        ),
    ]
