# Generated by Django 2.0.3 on 2018-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20180415_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='pkey',
            field=models.IntegerField(),
        ),
    ]
